version: '2'
services:
  # RESTful service
  rest:
    command: sh -c "yarn; nodemon --inspect=0.0.0.0:9229 app.js"
    build: 'rest'
    volumes:
      - "./rest:/var/rest"
    environment:
      TERM: xterm-256color
      DEBUG: '*'
      EXPRESS_PORT: 5000
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: todolist
      DB_HOST: mysql
      ORIGIN: "http://localhost:3000"
    ports:
      - 5000:5000
    links:
      - mysql
    stdin_open: true
    tty: true
    container_name: rest
  # Web app
  webapp:
    command: sh -c "yarn; npm start"
    build: 'spa'
    volumes:
     - "./spa:/var/spa"
    environment:
      TERM: xterm-256color
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    container_name: webapp
  # Main db
  mysql:
    image: mysql:5.7
    environment:
      TERM: xterm-256color
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    container_name: database