export const SET_CURRENT_DISPLAY_UPDATE = "SET_CURRENT_DISPLAY_UPDATE";
export const GET_CHOSEN_ADMIN_PROJECT = "GET_CHOSEN_ADMIN_PROJECT";
export const UPLOAD_PROJECT_PICTURE_REQUESTED =
  "UPLOAD_PROJECT_PICTURE_REQUESTED";
export const UPLOAD_UPDATE_ATTACHMENT_REQUESTED =
  "UPLOAD_UPDATE_ATTACHMENT_REQUESTED";
export const UPDATE_UPLOADED_PROJECT_ATTACHMENTS =
  "UPDATE_UPLOADED_PROJECT_ATTACHMENTS";
export const REMOVE_UPLOADED_PROJECT_ATTACHMENT =
  "REMOVE_UPLOADED_PROJECT_ATTACHMENT";
export const RESET_UPDATE_REDUCER_STATE = "RESET_UPDATE_REDUCER_STATE";
export const SET_CURRENT_UPDATE_ATTACHMENT = "SET_CURRENT_UPDATE_ATTACHMENT";

export const REMOVE_UPDATE_IMAGE_ATTACHMENT = "REMOVE_UPDATE_IMAGE_ATTACHMENT";
export const REMOVE_UPDATE_OTHER_ATTACHMENT = "REMOVE_UPDATE_OTHER_ATTACHMENT";
