export const GET_TODOS_REQUESTED = "GET_TODOS_REQUESTED";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";

export const ADD_TODOS_REQUESTED = "ADD_TODOS_REQUESTED";

export const DELETE_TODOS_REQUESTED = "DELETE_TODOS_REQUESTED";
